# https://taskfile.dev/usage/
version: '3'

dotenv: ['.env', '.env.defaults']

#includes:
#  prefix:
#    taskfile: ./path/to/file.yml
#    optional: true

output: prefixed
silent: true

#vars:
#  VARNAME: var_value

tasks:
  build:
    cmds:
      - gatsby build

  dev:
    cmds:
      - gatsby develop -H 0.0.0.0 -p 8000

  test:
    cmds:
      - echo "You're running a task!"
